#! /usr/bin/env node

var prompt  = require('prompt');
var request = require('request');
var colors  = require("colors/safe");
var progressBar = require('progress');

var STATIC_QUALIFIERS = ['exit', 'quit', 'help'];

prompt.message = colors.rainbow("DREWBOT ");
prompt.delimiter = '';

function createStory(name, description) {
  request({
    url: 'https://www.pivotaltracker.com/services/v5/projects/1937481/stories',
    headers: {
      'X-TrackerToken': process.env.TRACKER_TOKEN,
      'Content-Type' : 'application/json'
    },
    body: {
      "name": name,
      "description": description
    },
    json: true,
    method: 'post'
  }, function (error, response, body) {
    console.log(body);
    neuralLoop();
  });
}

function deleteStory(storyID) {
  request({
    url: 'https://www.pivotaltracker.com/services/v5/projects/1937481/stories/' + storyID,
    headers: {
      'X-TrackerToken': process.env.TRACKER_TOKEN,
    },
    method: 'delete'
  }, function(error, response, body) {
    if (response.statusCode) {
      console.log('Story deleted successfully.');
    } else {
      console.log(error);
    }
    neuralLoop();
  })
}

function analyzeStaticQualifier(qualifier) {
  switch (qualifier) {
    case 'exit':
    case 'quit':
      console.log('Time for DrewBot to go to bed.');
      process.exit();
      break;
    case 'help':
      console.log('\n Static qualifiers: ['+ STATIC_QUALIFIERS.join(" ") +']');

      console.log('\n DrewBot Protoface Usage Guide');

      console.log('\n ➡ Create a story:\n');
      console.log('  create - {"action": "create", "name": "New story", "description": "I am DrewBot"}');

      console.log('\n ➡ Delete a story:\n');
      console.log('  delete - {"action": "delete", "storyID": "1234"}');

      console.log('\n')
      break;
  }
  neuralLoop();
}

function analyzeVisualQualifier(qualifier) {
  try {

    var synapticResponse = JSON.parse(qualifier);

    switch (synapticResponse.action) {
      case 'create':
        createStory(synapticResponse.name, synapticResponse.description);
        break;
      case 'delete':
        deleteStory(synapticResponse.storyID);
        break;
    }
  } catch (e) {
    console.log('DrewBot is confused. DrewBot does not understand you.');
    neuralLoop();
  }
}

function neuralLoop() {
  prompt.get(['$'], function (err, result) {
    if (STATIC_QUALIFIERS.indexOf(result.$) > -1) {
      analyzeStaticQualifier(result.$);
    } else {
      analyzeVisualQualifier(result.$);
    }
  });
}

function wakeFromDream() {
  console.log('🤖  Initializing DrewBot Core Module...')

  var bar = new progressBar(':bar :percent', { total: 100 });
  var timer = setInterval(function () {
    bar.tick();
    if (bar.complete) {
      clearInterval(timer);

      bar = new progressBar(':bar :percent', { total: 100 });
      console.log('🤖  Reticulating Splines...');
      timer = setInterval(function () {
        bar.tick();
        if (bar.complete) {
          clearInterval(timer);
          console.log('🤖  Linking dependency learning network...');
          bar = new progressBar(':bar :percent', { total: 100 });
          timer = setInterval(function () {
            bar.tick();
            if (bar.complete) {
              clearInterval(timer);
              console.log('🤖  DrewBot 5000 is operational!\n');
              prompt.start();
              neuralLoop();
            }
          }, 10);
        }
      }, 10);
    }
  }, 10);
}

wakeFromDream();
